-- create
CREATE TABLE STUDENTS (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  age TEXT NOT NULL,
  address TEXT NOT NULL
);

-- insert
INSERT INTO STUDENTS VALUES (0001, 'Alex', 20, 'Moscow');
INSERT INTO STUDENTS VALUES (0002, 'Ann', 23, 'New York');
INSERT INTO STUDENTS VALUES (0003, 'Paul', 18, 'London');
INSERT INTO STUDENTS VALUES (0004, 'Kate', 27, 'Paris');
INSERT INTO STUDENTS VALUES (0005, 'Jane', 17, 'Moscow');
INSERT INTO STUDENTS VALUES (0006, 'Peter', 31, 'Tokyo');
INSERT INTO STUDENTS VALUES (0007, 'Sam', 35, 'Delhi');
INSERT INTO STUDENTS VALUES (0008, 'Robert', 17, 'Sydney');
INSERT INTO STUDENTS VALUES (0009, 'William', 25, 'Moscow');
INSERT INTO STUDENTS VALUES (0010, 'Susan', 33, 'Los Angeles');

-- fetch 
SELECT name FROM STUDENTS WHERE age >= 18 AND age < 30 AND address = 'Moscow';